WifiCountryCode: "AU"
VideoAntiFlickerRate: 60
VideoQualityDefault: "default"
NotifyRegisteredAndStatusUpdate: true
NotifyOnMotionAlert: true
NotifyOnMotionTimeoutAlert: false
NotifyOnAudioAlert: false
NotifyOnButtonPressAlert: true
MotionRecordingWebHookUrl: "http://homeassistant.local:11080/endpoint/@scrypted/arlo-local/public/motionDetected"
MotionTimeoutWebHookUrl: "changeme"
AudioRecordingWebHookUrl: "http://homeassistant.local:11080/endpoint/@scrypted/arlo-local/public/"
UserRecordingWebHookUrl: "http://homeassistant.local:11080/endpoint/@scrypted/arlo-local/public/"
StatusUpdateWebHookUrl: "http://homeassistant.local:11080/endpoint/@scrypted/arlo-local/public/statusUpdated"
RegistrationWebHookUrl: "http://homeassistant.local:11080/endpoint/@scrypted/arlo-local/public/registered"
ButtonPressWebHookUrl: "http://homeassistant.local:11080/endpoint/@scrypted/arlo-local/public/buttonPressed"
